/**
 * @file form_script_generator.cpp
 * @brief FormScriptGenerator — DSL + on-disk кэш кернелов для getX
 *
 * Генерирует OpenCL kernel с #define параметрами и Philox PRNG.
 * On-disk кэш: .cl source + binary, manifest.json, versioning.
 *
 * @author Кодо (AI Assistant)
 * @date 2026-02-17
 */

#include "generators/form_script_generator.hpp"
#include <stdexcept>
#include <sstream>
#include <fstream>
#include <cstring>
#include <chrono>
#include <iomanip>
#include <algorithm>
#include <sys/stat.h>

// Filesystem: C++17
#if __has_include(<filesystem>)
#include <filesystem>
namespace fs = std::filesystem;
#else
#error "C++17 <filesystem> required"
#endif

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

// Path to kernels/ set by CMake (fallback: relative)
#ifndef SIGNAL_GENERATORS_KERNELS_DIR
#define SIGNAL_GENERATORS_KERNELS_DIR "modules/signal_generators/kernels"
#endif

namespace signal_gen {

// ════════════════════════════════════════════════════════════════════════════
// PRNG source (shared with FormSignalGenerator)
// ════════════════════════════════════════════════════════════════════════════

static const char* PRNG_SOURCE = R"CL(
// Philox-2x32-10: counter-based PRNG
uint2 philox2x32_round(uint2 ctr, uint key) {
    const uint PHILOX_M = 0xD2511F53u;
    uint hi = mul_hi(ctr.x, PHILOX_M);
    uint lo = ctr.x * PHILOX_M;
    return (uint2)(hi ^ key ^ ctr.y, lo);
}

uint2 philox2x32_10(uint2 ctr, uint key) {
    const uint PHILOX_BUMP = 0x9E3779B9u;
    ctr = philox2x32_round(ctr, key); key += PHILOX_BUMP;
    ctr = philox2x32_round(ctr, key); key += PHILOX_BUMP;
    ctr = philox2x32_round(ctr, key); key += PHILOX_BUMP;
    ctr = philox2x32_round(ctr, key); key += PHILOX_BUMP;
    ctr = philox2x32_round(ctr, key); key += PHILOX_BUMP;
    ctr = philox2x32_round(ctr, key); key += PHILOX_BUMP;
    ctr = philox2x32_round(ctr, key); key += PHILOX_BUMP;
    ctr = philox2x32_round(ctr, key); key += PHILOX_BUMP;
    ctr = philox2x32_round(ctr, key); key += PHILOX_BUMP;
    ctr = philox2x32_round(ctr, key);
    return ctr;
}

float philox_uniform(uint id, uint seed) {
    uint2 ctr = (uint2)(id, seed);
    uint2 rnd = philox2x32_10(ctr, 0xAB12CD34u);
    return (float)(rnd.x) / 4294967296.0f;
}
)CL";

// ════════════════════════════════════════════════════════════════════════════
// Constructor / Destructor
// ════════════════════════════════════════════════════════════════════════════

FormScriptGenerator::FormScriptGenerator(drv_gpu_lib::IBackend* backend)
    : backend_(backend) {
  if (!backend_ || !backend_->IsInitialized()) {
    throw std::runtime_error(
        "FormScriptGenerator: backend is null or not initialized");
  }
  context_ = static_cast<cl_context>(backend_->GetNativeContext());
  queue_   = static_cast<cl_command_queue>(backend_->GetNativeQueue());
  device_  = static_cast<cl_device_id>(backend_->GetNativeDevice());
}

FormScriptGenerator::~FormScriptGenerator() {
  ReleaseGpuResources();
}

FormScriptGenerator::FormScriptGenerator(FormScriptGenerator&& o) noexcept
    : backend_(o.backend_), params_(o.params_),
      kernel_source_(std::move(o.kernel_source_)),
      loaded_kernel_name_(std::move(o.loaded_kernel_name_)),
      context_(o.context_), queue_(o.queue_),
      device_(o.device_), program_(o.program_) {
  o.program_ = nullptr;
}

FormScriptGenerator& FormScriptGenerator::operator=(
    FormScriptGenerator&& o) noexcept {
  if (this != &o) {
    ReleaseGpuResources();
    backend_ = o.backend_;
    params_ = o.params_;
    kernel_source_ = std::move(o.kernel_source_);
    loaded_kernel_name_ = std::move(o.loaded_kernel_name_);
    context_ = o.context_;
    queue_ = o.queue_;
    device_ = o.device_;
    program_ = o.program_;
    o.program_ = nullptr;
  }
  return *this;
}

// ════════════════════════════════════════════════════════════════════════════
// Params
// ════════════════════════════════════════════════════════════════════════════

void FormScriptGenerator::SetParams(const FormParams& params) {
  params_ = params;
  ReleaseGpuResources();  // invalidate compiled program
}

void FormScriptGenerator::SetParamsFromString(const std::string& str) {
  SetParams(FormParams::ParseFromString(str));
}

// ════════════════════════════════════════════════════════════════════════════
// DSL Script Generation
// ════════════════════════════════════════════════════════════════════════════

std::string FormScriptGenerator::GenerateScript() const {
  std::ostringstream s;
  auto mode = params_.GetTauMode();

  s << "// FormSignal DSL — auto-generated by FormScriptGenerator\n";
  s << "// Formula: X = a*norm*exp(j*(2pi*f0*t + pi*fdev/ti*((t-ti/2)^2) + phi))\n";
  s << "//            + an*norm*(randn_re + j*randn_im)\n";
  s << "// Window:  X = 0 if t < 0 or t > ti - dt\n\n";

  s << "[Params]\n";
  s << "ANTENNAS = " << params_.antennas << "\n";
  s << "POINTS = " << params_.points << "\n";
  s << "FS = " << params_.fs << "\n";
  s << "F0 = " << params_.f0 << "\n";
  s << "A = " << params_.amplitude << "\n";
  s << "AN = " << params_.noise_amplitude << "\n";
  s << "PHI = " << params_.phase << "\n";
  s << "FDEV = " << params_.fdev << "\n";
  s << "NORM = " << params_.norm << "\n";

  if (params_.noise_seed != 0)
    s << "NOISE_SEED = " << params_.noise_seed << "\n";

  s << "\n// --- Tau mode: ";
  if (mode == TauMode::LINEAR) {
    s << "LINEAR ---\n";
    s << "TAU_BASE = " << params_.tau_base << "\n";
    s << "TAU_STEP = " << params_.tau_step << "\n";
  } else if (mode == TauMode::RANDOM) {
    s << "RANDOM ---\n";
    s << "TAU_MIN = " << params_.tau_min << "\n";
    s << "TAU_MAX = " << params_.tau_max << "\n";
    s << "TAU_SEED = " << params_.tau_seed << "\n";
  } else {
    s << "FIXED ---\n";
    s << "TAU_BASE = " << params_.tau_base << "\n";
  }

  s << "\n[Defs]\n";
  s << "float dt = 1.0f / FS;\n";
  s << "float ti = (float)POINTS * dt;\n";

  if (mode == TauMode::LINEAR) {
    s << "float tau = TAU_BASE + (float)ID * TAU_STEP;\n";
  } else if (mode == TauMode::RANDOM) {
    s << "float tau = TAU_MIN + philox_uniform(ID, TAU_SEED) * (TAU_MAX - TAU_MIN);\n";
  } else {
    s << "float tau = TAU_BASE;\n";
  }

  s << "float t = (float)T * dt + tau;\n";
  s << "int in_window = (t >= 0.0f && t <= ti - dt) ? 1 : 0;\n";
  s << "float t_centered = t - ti * 0.5f;\n";
  s << "float phase = 2.0f * M_PI_F * F0 * t"
       " + M_PI_F * FDEV / ti * (t_centered * t_centered) + PHI;\n";

  s << "\n[Signal]\n";
  s << "float sig_re = in_window ? (A * NORM * cos(phase)) : 0.0f;\n";
  s << "float sig_im = in_window ? (A * NORM * sin(phase)) : 0.0f;\n";

  if (params_.noise_amplitude > 0.0) {
    s << "// Noise via Philox + Box-Muller (builtin)\n";
    s << "float noise_re = in_window ? (AN * NORM * randn_re) : 0.0f;\n";
    s << "float noise_im = in_window ? (AN * NORM * randn_im) : 0.0f;\n";
    s << "res_re = sig_re + noise_re;\n";
    s << "res_im = sig_im + noise_im;\n";
  } else {
    s << "res_re = sig_re;\n";
    s << "res_im = sig_im;\n";
  }

  return s.str();
}

// ════════════════════════════════════════════════════════════════════════════
// OpenCL Kernel Source Generation
// ════════════════════════════════════════════════════════════════════════════

std::string FormScriptGenerator::GenerateKernelSource() const {
  std::ostringstream k;
  auto mode = params_.GetTauMode();

  float dt = static_cast<float>(params_.GetDt());
  float ti = static_cast<float>(params_.GetDuration());

  uint32_t noise_seed = params_.noise_seed;
  if (noise_seed == 0 && params_.noise_amplitude > 0.0) {
    noise_seed = static_cast<uint32_t>(
        std::chrono::high_resolution_clock::now().time_since_epoch().count()
        & 0xFFFFFFFF);
  }

  // Header
  k << "// Auto-generated by FormScriptGenerator\n";
  k << "// Formula: getX with Philox PRNG + Box-Muller noise\n\n";

  // Constants as #define
  k << "#define FSG_ANTENNAS " << params_.antennas << "u\n";
  k << "#define FSG_POINTS " << params_.points << "u\n";
  k << "#define FSG_DT " << std::scientific << dt << "f\n";
  k << "#define FSG_TI " << std::scientific << ti << "f\n";
  k << "#define FSG_F0 " << std::scientific << static_cast<float>(params_.f0) << "f\n";
  k << "#define FSG_AMPLITUDE " << std::scientific << static_cast<float>(params_.amplitude) << "f\n";
  k << "#define FSG_NOISE_AMP " << std::scientific << static_cast<float>(params_.noise_amplitude) << "f\n";
  k << "#define FSG_PHASE " << std::scientific << static_cast<float>(params_.phase) << "f\n";
  k << "#define FSG_FDEV " << std::scientific << static_cast<float>(params_.fdev) << "f\n";
  k << "#define FSG_NORM " << std::scientific << static_cast<float>(params_.norm) << "f\n";
  k << "#define FSG_NOISE_SEED " << noise_seed << "u\n";
  k << "#define FSG_TAU_MODE " << static_cast<uint32_t>(mode) << "u\n";

  if (mode == TauMode::LINEAR || mode == TauMode::FIXED) {
    k << "#define FSG_TAU_BASE " << std::scientific << static_cast<float>(params_.tau_base) << "f\n";
    k << "#define FSG_TAU_STEP " << std::scientific << static_cast<float>(params_.tau_step) << "f\n";
  }
  if (mode == TauMode::RANDOM) {
    k << "#define FSG_TAU_MIN " << std::scientific << static_cast<float>(params_.tau_min) << "f\n";
    k << "#define FSG_TAU_MAX " << std::scientific << static_cast<float>(params_.tau_max) << "f\n";
    k << "#define FSG_TAU_SEED " << params_.tau_seed << "u\n";
  }

  k << "\n";

  // PRNG functions
  k << PRNG_SOURCE << "\n";

  // Main kernel — only 1 argument (output)!
  k << "__kernel void form_script_signal(__global float2* output) {\n";
  k << "    const uint gid = get_global_id(0);\n";
  k << "    if (gid >= FSG_ANTENNAS * FSG_POINTS) return;\n";
  k << "\n";
  k << "    const uint ID = gid / FSG_POINTS;\n";
  k << "    const uint T  = gid % FSG_POINTS;\n";
  k << "\n";

  // Tau per-channel
  k << "    // Tau per-channel\n";
  if (mode == TauMode::FIXED) {
    k << "    const float tau = FSG_TAU_BASE;\n";
  } else if (mode == TauMode::LINEAR) {
    k << "    const float tau = FSG_TAU_BASE + (float)ID * FSG_TAU_STEP;\n";
  } else {
    k << "    const float tau = FSG_TAU_MIN + philox_uniform(ID, FSG_TAU_SEED)"
         " * (FSG_TAU_MAX - FSG_TAU_MIN);\n";
  }

  k << "\n";
  k << "    // Time + window\n";
  k << "    const float t = (float)T * FSG_DT + tau;\n";
  k << "    if (t < 0.0f || t > FSG_TI - FSG_DT) {\n";
  k << "        output[gid] = (float2)(0.0f, 0.0f);\n";
  k << "        return;\n";
  k << "    }\n";
  k << "\n";

  // Signal phase
  k << "    // Phase: 2pi*f0*t + pi*fdev/ti*((t-ti/2)^2) + phi\n";
  k << "    const float t_c = t - FSG_TI * 0.5f;\n";
  k << "    const float phase = 2.0f * M_PI_F * FSG_F0 * t\n";
  k << "                      + M_PI_F * FSG_FDEV / FSG_TI * (t_c * t_c)\n";
  k << "                      + FSG_PHASE;\n";
  k << "\n";
  k << "    float re = FSG_AMPLITUDE * FSG_NORM * cos(phase);\n";
  k << "    float im = FSG_AMPLITUDE * FSG_NORM * sin(phase);\n";

  // Noise
  if (params_.noise_amplitude > 0.0) {
    k << "\n";
    k << "    // Noise: Philox + Box-Muller\n";
    k << "    uint2 n_ctr = (uint2)(gid, FSG_NOISE_SEED);\n";
    k << "    uint2 n_rnd = philox2x32_10(n_ctr, 0xCD9E8D57u);\n";
    k << "    float u1 = (float)(n_rnd.x) / 4294967296.0f + 1e-10f;\n";
    k << "    float u2 = (float)(n_rnd.y) / 4294967296.0f;\n";
    k << "    float r = sqrt(-2.0f * log(u1));\n";
    k << "    float theta = 2.0f * M_PI_F * u2;\n";
    k << "    re += FSG_NOISE_AMP * FSG_NORM * r * cos(theta);\n";
    k << "    im += FSG_NOISE_AMP * FSG_NORM * r * sin(theta);\n";
  }

  k << "\n";
  k << "    output[gid] = (float2)(re, im);\n";
  k << "}\n";

  return k.str();
}

// ════════════════════════════════════════════════════════════════════════════
// Compile
// ════════════════════════════════════════════════════════════════════════════

void FormScriptGenerator::Compile() {
  kernel_source_ = GenerateKernelSource();
  CompileSource(kernel_source_);
}

void FormScriptGenerator::CompileSource(const std::string& source) {
  ReleaseGpuResources();

  cl_int err;
  const char* src = source.c_str();
  size_t src_len = source.size();

  program_ = clCreateProgramWithSource(context_, 1, &src, &src_len, &err);
  if (err != CL_SUCCESS) {
    throw std::runtime_error(
        "FormScriptGenerator: clCreateProgramWithSource failed: "
        + std::to_string(err));
  }

  err = clBuildProgram(program_, 1, &device_,
                       "-cl-fast-relaxed-math", nullptr, nullptr);
  if (err != CL_SUCCESS) {
    size_t log_size = 0;
    clGetProgramBuildInfo(program_, device_, CL_PROGRAM_BUILD_LOG,
                          0, nullptr, &log_size);
    std::vector<char> log(log_size + 1, '\0');
    clGetProgramBuildInfo(program_, device_, CL_PROGRAM_BUILD_LOG,
                          log_size, log.data(), nullptr);
    clReleaseProgram(program_);
    program_ = nullptr;

    std::string msg = "FormScriptGenerator: kernel build failed!\n\n";
    msg += "=== Source ===\n" + source + "\n";
    msg += "=== Build log ===\n" + std::string(log.data()) + "\n";
    throw std::runtime_error(msg);
  }

  kernel_source_ = source;
}

// ════════════════════════════════════════════════════════════════════════════
// Generate
// ════════════════════════════════════════════════════════════════════════════

cl_mem FormScriptGenerator::Generate() {
  if (!program_) {
    throw std::runtime_error(
        "FormScriptGenerator::Generate: not compiled (call Compile() or LoadKernel())");
  }

  size_t total = GetTotalSamples();
  size_t buf_size = total * sizeof(std::complex<float>);

  cl_int err;
  cl_mem output = clCreateBuffer(context_, CL_MEM_READ_WRITE,
                                  buf_size, nullptr, &err);
  if (err != CL_SUCCESS) {
    throw std::runtime_error(
        "FormScriptGenerator::Generate: clCreateBuffer failed: "
        + std::to_string(err));
  }

  cl_kernel k = clCreateKernel(program_, "form_script_signal", &err);
  if (err != CL_SUCCESS) {
    clReleaseMemObject(output);
    throw std::runtime_error(
        "FormScriptGenerator::Generate: clCreateKernel failed: "
        + std::to_string(err));
  }

  err = clSetKernelArg(k, 0, sizeof(cl_mem), &output);
  if (err != CL_SUCCESS) {
    clReleaseKernel(k);
    clReleaseMemObject(output);
    throw std::runtime_error(
        "FormScriptGenerator::Generate: clSetKernelArg failed");
  }

  size_t local_size = 256;
  size_t global_size = ((total + local_size - 1) / local_size) * local_size;

  err = clEnqueueNDRangeKernel(queue_, k, 1, nullptr,
                                &global_size, &local_size,
                                0, nullptr, nullptr);
  clReleaseKernel(k);

  if (err != CL_SUCCESS) {
    clReleaseMemObject(output);
    throw std::runtime_error(
        "FormScriptGenerator::Generate: enqueue failed: "
        + std::to_string(err));
  }

  clFinish(queue_);
  return output;
}

std::vector<std::vector<std::complex<float>>>
FormScriptGenerator::GenerateToCpu() {
  cl_mem gpu_buf = Generate();

  size_t total = GetTotalSamples();
  std::vector<std::complex<float>> flat(total);

  cl_int err = clEnqueueReadBuffer(queue_, gpu_buf, CL_TRUE, 0,
                                    total * sizeof(std::complex<float>),
                                    flat.data(), 0, nullptr, nullptr);
  clReleaseMemObject(gpu_buf);

  if (err != CL_SUCCESS) {
    throw std::runtime_error(
        "FormScriptGenerator::GenerateToCpu: readback failed");
  }

  std::vector<std::vector<std::complex<float>>> result(params_.antennas);
  for (uint32_t a = 0; a < params_.antennas; ++a) {
    size_t offset = static_cast<size_t>(a) * params_.points;
    result[a].assign(flat.begin() + offset,
                     flat.begin() + offset + params_.points);
  }
  return result;
}

// ════════════════════════════════════════════════════════════════════════════
// On-disk cache: Save
// ════════════════════════════════════════════════════════════════════════════

void FormScriptGenerator::SaveKernel(const std::string& name,
                                      const std::string& comment) {
  if (!program_) {
    throw std::runtime_error(
        "FormScriptGenerator::SaveKernel: not compiled");
  }
  if (name.empty()) {
    throw std::runtime_error(
        "FormScriptGenerator::SaveKernel: name cannot be empty");
  }

  std::string kdir = GetKernelsDir();
  std::string bdir = GetKernelsBinDir();

  // Ensure directories exist
  fs::create_directories(bdir);

  // Version old files if they exist
  VersionOldFiles(name);

  // Save .cl source
  std::string cl_path = kdir + "/" + name + ".cl";
  {
    std::ofstream f(cl_path);
    if (!f.is_open()) {
      throw std::runtime_error(
          "FormScriptGenerator::SaveKernel: cannot write " + cl_path);
    }
    f << kernel_source_;
  }

  // Save binary
  auto binary = GetProgramBinary();
  std::string bin_path = bdir + "/" + name + "_opencl.bin";
  {
    std::ofstream f(bin_path, std::ios::binary);
    if (!f.is_open()) {
      throw std::runtime_error(
          "FormScriptGenerator::SaveKernel: cannot write " + bin_path);
    }
    f.write(reinterpret_cast<const char*>(binary.data()), binary.size());
  }

  // Update manifest
  WriteManifestEntry(name, comment);

  loaded_kernel_name_ = name;
}

// ════════════════════════════════════════════════════════════════════════════
// On-disk cache: Load
// ════════════════════════════════════════════════════════════════════════════

void FormScriptGenerator::LoadKernel(const std::string& name) {
  std::string kdir = GetKernelsDir();
  std::string bdir = GetKernelsBinDir();
  std::string bin_path = bdir + "/" + name + "_opencl.bin";
  std::string cl_path = kdir + "/" + name + ".cl";

  // Try binary first (fast path)
  if (fs::exists(bin_path)) {
    std::ifstream f(bin_path, std::ios::binary | std::ios::ate);
    if (f.is_open()) {
      auto size = f.tellg();
      f.seekg(0, std::ios::beg);
      std::vector<unsigned char> binary(size);
      f.read(reinterpret_cast<char*>(binary.data()), size);

      try {
        LoadFromBinary(binary);
        // Also load source for inspection
        if (fs::exists(cl_path)) {
          std::ifstream sf(cl_path);
          std::ostringstream ss;
          ss << sf.rdbuf();
          kernel_source_ = ss.str();
        }
        loaded_kernel_name_ = name;
        return;
      } catch (...) {
        // Binary load failed, fall through to source
      }
    }
  }

  // Try source (compile + save binary)
  if (fs::exists(cl_path)) {
    std::ifstream f(cl_path);
    if (!f.is_open()) {
      throw std::runtime_error(
          "FormScriptGenerator::LoadKernel: cannot read " + cl_path);
    }
    std::ostringstream ss;
    ss << f.rdbuf();
    std::string source = ss.str();

    LoadFromSource(source);

    // Save binary for next time
    try {
      fs::create_directories(bdir);
      auto binary = GetProgramBinary();
      std::ofstream bf(bin_path, std::ios::binary);
      if (bf.is_open()) {
        bf.write(reinterpret_cast<const char*>(binary.data()), binary.size());
      }
    } catch (...) {
      // Non-critical: binary save failed, source still works
    }

    loaded_kernel_name_ = name;
    return;
  }

  throw std::runtime_error(
      "FormScriptGenerator::LoadKernel: kernel '" + name
      + "' not found (checked: " + bin_path + ", " + cl_path + ")");
}

// ════════════════════════════════════════════════════════════════════════════
// List kernels
// ════════════════════════════════════════════════════════════════════════════

std::vector<std::string> FormScriptGenerator::ListKernels() const {
  std::vector<std::string> names;
  std::string manifest_path = GetKernelsDir() + "/manifest.json";

  if (!fs::exists(manifest_path)) return names;

  // Simple JSON parsing (no external deps): find "name": "value" pairs
  std::ifstream f(manifest_path);
  std::string content((std::istreambuf_iterator<char>(f)),
                       std::istreambuf_iterator<char>());

  // Find all "name" keys after "kernels" section
  std::string search = "\"name\"";
  size_t pos = 0;
  while ((pos = content.find(search, pos)) != std::string::npos) {
    pos += search.size();
    // Skip whitespace and colon
    while (pos < content.size() && (content[pos] == ' ' || content[pos] == ':' || content[pos] == '"'))
      ++pos;
    size_t end = content.find('"', pos);
    if (end != std::string::npos) {
      names.push_back(content.substr(pos, end - pos));
      pos = end + 1;
    }
  }

  return names;
}

// ════════════════════════════════════════════════════════════════════════════
// Static paths
// ════════════════════════════════════════════════════════════════════════════

std::string FormScriptGenerator::GetKernelsDir() {
  return SIGNAL_GENERATORS_KERNELS_DIR;
}

std::string FormScriptGenerator::GetKernelsBinDir() {
  return std::string(SIGNAL_GENERATORS_KERNELS_DIR) + "/bin";
}

// ════════════════════════════════════════════════════════════════════════════
// Private helpers
// ════════════════════════════════════════════════════════════════════════════

void FormScriptGenerator::ReleaseGpuResources() {
  if (program_) {
    clReleaseProgram(program_);
    program_ = nullptr;
  }
}

void FormScriptGenerator::VersionOldFiles(const std::string& name) const {
  std::string kdir = GetKernelsDir();
  std::string bdir = GetKernelsBinDir();
  std::string cl_path = kdir + "/" + name + ".cl";
  std::string bin_path = bdir + "/" + name + "_opencl.bin";

  bool cl_exists = fs::exists(cl_path);
  bool bin_exists = fs::exists(bin_path);

  if (!cl_exists && !bin_exists) return;

  // Find next free suffix: _00, _01, ...
  int suffix = 0;
  while (true) {
    char buf[8];
    snprintf(buf, sizeof(buf), "_%02d", suffix);
    std::string s(buf);

    std::string old_cl = kdir + "/" + name + s + ".cl";
    std::string old_bin = bdir + "/" + name + "_opencl" + s + ".bin";

    if (!fs::exists(old_cl) && !fs::exists(old_bin)) {
      // Rename current → _XX
      if (cl_exists)  fs::rename(cl_path, old_cl);
      if (bin_exists) fs::rename(bin_path, old_bin);
      return;
    }
    ++suffix;
    if (suffix > 99) break;  // safety
  }
}

void FormScriptGenerator::WriteManifestEntry(
    const std::string& name, const std::string& comment) const {
  std::string manifest_path = GetKernelsDir() + "/manifest.json";

  // Read existing manifest or start fresh
  std::string content;
  if (fs::exists(manifest_path)) {
    std::ifstream f(manifest_path);
    content.assign((std::istreambuf_iterator<char>(f)),
                    std::istreambuf_iterator<char>());
  }

  // Check if this name already exists — update or append
  std::string timestamp = GetTimestamp();
  std::string params_str = ParamsToString();

  // Build new entry JSON
  std::ostringstream entry;
  entry << "    {\n";
  entry << "      \"name\": \"" << name << "\",\n";
  entry << "      \"comment\": \"" << comment << "\",\n";
  entry << "      \"created\": \"" << timestamp << "\",\n";
  entry << "      \"params\": \"" << params_str << "\",\n";
  entry << "      \"backend\": \"opencl\"\n";
  entry << "    }";

  // Simple approach: rewrite manifest with all existing + new/updated
  // Parse existing entries (skip entry with same name)
  std::vector<std::string> entries;
  if (!content.empty()) {
    // Find entries between [ and ]
    size_t arr_start = content.find('[');
    size_t arr_end = content.rfind(']');
    if (arr_start != std::string::npos && arr_end != std::string::npos) {
      std::string arr = content.substr(arr_start + 1, arr_end - arr_start - 1);

      // Split by "}" and reconstruct
      size_t pos = 0;
      while (true) {
        size_t obj_start = arr.find('{', pos);
        if (obj_start == std::string::npos) break;
        size_t obj_end = arr.find('}', obj_start);
        if (obj_end == std::string::npos) break;

        std::string obj = arr.substr(obj_start, obj_end - obj_start + 1);

        // Check if this is the same name
        bool same_name = false;
        std::string name_check = "\"name\": \"" + name + "\"";
        if (obj.find(name_check) != std::string::npos) {
          same_name = true;
        }
        // Also check without space
        name_check = "\"name\":\"" + name + "\"";
        if (obj.find(name_check) != std::string::npos) {
          same_name = true;
        }

        if (!same_name) {
          // Re-indent
          entries.push_back("    " + obj);
        }

        pos = obj_end + 1;
      }
    }
  }

  // Add new entry
  entries.push_back(entry.str());

  // Write manifest
  std::ofstream f(manifest_path);
  f << "{\n";
  f << "  \"version\": 1,\n";
  f << "  \"kernels\": [\n";
  for (size_t i = 0; i < entries.size(); ++i) {
    f << entries[i];
    if (i + 1 < entries.size()) f << ",";
    f << "\n";
  }
  f << "  ]\n";
  f << "}\n";
}

std::vector<unsigned char> FormScriptGenerator::GetProgramBinary() const {
  if (!program_) {
    throw std::runtime_error("GetProgramBinary: no compiled program");
  }

  size_t binary_size = 0;
  cl_int err = clGetProgramInfo(program_, CL_PROGRAM_BINARY_SIZES,
                                 sizeof(size_t), &binary_size, nullptr);
  if (err != CL_SUCCESS || binary_size == 0) {
    throw std::runtime_error("GetProgramBinary: cannot get binary size");
  }

  std::vector<unsigned char> binary(binary_size);
  unsigned char* ptrs[] = { binary.data() };
  err = clGetProgramInfo(program_, CL_PROGRAM_BINARIES,
                          sizeof(unsigned char*), ptrs, nullptr);
  if (err != CL_SUCCESS) {
    throw std::runtime_error("GetProgramBinary: cannot get binary");
  }

  return binary;
}

void FormScriptGenerator::LoadFromBinary(
    const std::vector<unsigned char>& binary) {
  ReleaseGpuResources();

  cl_int err, binary_status;
  size_t bin_size = binary.size();
  const unsigned char* bin_ptr = binary.data();

  program_ = clCreateProgramWithBinary(
      context_, 1, &device_, &bin_size, &bin_ptr, &binary_status, &err);

  if (err != CL_SUCCESS || binary_status != CL_SUCCESS) {
    program_ = nullptr;
    throw std::runtime_error(
        "LoadFromBinary: clCreateProgramWithBinary failed");
  }

  err = clBuildProgram(program_, 1, &device_,
                       "-cl-fast-relaxed-math", nullptr, nullptr);
  if (err != CL_SUCCESS) {
    clReleaseProgram(program_);
    program_ = nullptr;
    throw std::runtime_error("LoadFromBinary: clBuildProgram failed");
  }
}

void FormScriptGenerator::LoadFromSource(const std::string& source) {
  CompileSource(source);
}

std::string FormScriptGenerator::GetTimestamp() {
  auto now = std::chrono::system_clock::now();
  auto t = std::chrono::system_clock::to_time_t(now);
  std::tm tm_buf;
  localtime_r(&t, &tm_buf);

  char buf[32];
  std::strftime(buf, sizeof(buf), "%Y-%m-%dT%H:%M:%S", &tm_buf);
  return std::string(buf);
}

std::string FormScriptGenerator::ParamsToString() const {
  std::ostringstream s;
  s << "fs=" << params_.fs
    << ",f0=" << params_.f0
    << ",a=" << params_.amplitude
    << ",an=" << params_.noise_amplitude
    << ",antennas=" << params_.antennas
    << ",points=" << params_.points;
  if (params_.fdev != 0.0) s << ",fdev=" << params_.fdev;
  if (params_.phase != 0.0) s << ",phi=" << params_.phase;
  if (params_.tau_base != 0.0) s << ",tau=" << params_.tau_base;
  if (params_.tau_step != 0.0) s << ",tau_step=" << params_.tau_step;
  return s.str();
}

} // namespace signal_gen
