
[Interface]
PrivateKey = yBouAJMxkeDny8ISwcGS5C83pPL6569d6ido5gZdilE=
Address = 10.8.0.2/24
DNS = 1.1.1.1

[Peer]
PublicKey = sccLjwL8E3ZwxZfoyxK0av+jCmmCNrqSZrD/DO6e2S4=
PresharedKey = dx727fV1WVESb0JoCtcCxJM4GSFzRNpWJvo6eZbwJH0=
AllowedIPs = 0.0.0.0/0, ::/0
PersistentKeepalive = 0
Endpoint = 195.133.21.235:51820